name: Create release
description: Create a release for a version tag

inputs:
  secrets:
    description: JSON representation of workflow secrets object
    required: true
  vars:
    description: JSON representation of workflow vars object
    required: true
  token:
    description: GitHub token passed directly
    required: true

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Test secret 1
      if: contains(fromJSON(inputs.secrets).GITHUB_TOKEN, '*')
      shell: bash
      run: |
        exit 1

    - name: Test secret 3
      if: contains(fromJSON(inputs.secrets).GITHUB_TOKEN, '***')
      shell: bash
      run: |
        exit 1

    - name: Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: true
        prerelease: contains(${{ github.ref_name }}, '-')
