# This action requires that Node be installed, project be checked out, and "npm ci" be run before calling.
# For more information see https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages.
name: Build project and publish to NPM

inputs:
  project:
    description: Project to be built and published
    required: true
  no_test:
    description: If true, test is not run
    required: false
  node_auth_token:
    description: If provided, project is published to NPM
    required: false
  terminal_pre_build:
    description: If true, a terminal session is opened before the build step is run
    required: false
  terminal_post_build:
    description: If true, a terminal session is opened after the build step is run
    required: false

runs:
  using: composite

  steps:
    - name: Start terminal session (pre build)
      if: inputs.terminal_pre_build == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Build ${{ inputs.project }}
      shell: bash
      run: |
        # This is necessary to work around platform-specific optional dependencies bug
        # (https://github.com/npm/cli/issues/4828).
        npm install @rollup/rollup-linux-x64-gnu

        # All projects have build script.
        npm run build

    - name: Start terminal session (post build)
      if: inputs.terminal_post_build == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Test ${{ inputs.project }}
      if: inputs.no_test != 'true'
      shell: bash
      run: |
        # Project must have test script.
        npm test

    - name: Publish ${{ inputs.project }}
      # Publish is valid only as part of release.
      if: github.event_name == 'release' && inputs.npm_token != null
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node_auth_token }}
      run: |
        npm publish --access public
