name: Build project and publish to NPM

inputs:
  project:
    description: Project to be built and published
    required: true
  node_version:
    description: Node version
    required: true
  node_auth_token:
    description: Node authentication token for publishing to NPM
    required: true
  no_test:
    description: If true, test is not run
    required: false
  terminal_pre_build:
    description: If true, terminal session is started before build step is run
    required: false
  terminal_post_build:
    description: If true, terminal session is started after build step is run
    required: false

runs:
  using: composite

  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: https://registry.npmjs.org/

    - name: Checkout
      uses: actions/checkout@v4

    - name: Start terminal session (pre build)
      if: inputs.terminal_pre_build == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Build ${{ inputs.project }}
      shell: bash
      run: |
        # Removing package-lock.json is necessary to force download of all dependencies including linked dependencies.
        rm package-lock.json
        
        npm install
        
        # This is necessary to work around platform-specific optional dependencies bug
        # (https://github.com/npm/cli/issues/4828).
        npm install @rollup/rollup-linux-x64-gnu

        # All projects have build script.
        npm run build

    - name: Start terminal session (post build)
      if: inputs.terminal_post_build == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Test ${{ inputs.project }}
      if: inputs.no_test != 'true'
      shell: bash
      run: |
        # Project must have test script.
        npm run test

    - name: Publish ${{ inputs.project }}
      # Publish is valid only as part of release.
      if: github.event_name == 'release'
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node_auth_token }}
      run: |
        npm publish --access public
