# This action requires that Node be installed, project be checked out, and "npm ci" be run before calling.
# For more information see https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages.
name: Build project and publish to NPM

inputs:
  project:
    description: Project to be built and published
    required: true
  no_test:
    description: If true, test is not run
    required: false
  no_publish:
    description: If true, publish is not run
    required: false

runs:
  using: composite

  steps:
    - name: Dump vars
      if: vars.DUMP_VARS == 'true'
      shell: bash
      run: |
        cat << EOF
        ${{ toJSON(vars) }}
        EOF

    - name: Dump GitHub context
      if: vars.DUMP_GITHUB_CONTEXT == 'true'
      shell: bash
      run: |
        cat << EOF
        ${{ toJSON(github) }}
        EOF

    - name: Start terminal session (pre build)
      if: vars.TERMINAL_PRE_BUILD == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Build ${{ inputs.project }}
      shell: bash
      run: |
        # This is necessary to work around platform-specific optional dependencies bug
        # (https://github.com/npm/cli/issues/4828).
        npm install @rollup/rollup-linux-x64-gnu

        # All projects have build script.
        npm run build

    - name: Start terminal session (post build)
      if: vars.TERMINAL_POST_BUILD == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Test ${{ inputs.project }}
      if: inputs.no_test != 'true'
      shell: bash
      run: |
        # Project must have test script.
        npm test

    - name: Publish ${{ inputs.project }}
      # Publish is valid only as part of release.
      if: github.event_name == 'release' && inputs.no_publish != 'true'
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm publish --access public
