name: Build, test, publish
description: Build, optionally test, and optionally publish to NPM

inputs:
  secrets:
    description: JSON representation of workflow secrets object
    required: true
  vars:
    description: JSON representation of workflow vars object
    required: true

runs:
  using: composite

  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ fromJSON(inputs.vars).NODE_VERSION }}
        registry-url: https://registry.npmjs.org/

    - name: Checkout
      uses: actions/checkout@v4

    - name: Start terminal session (pre build)
      if: fromJSON(inputs.vars).TERMINAL_PRE_BUILD == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Build
      shell: bash
      run: |
        npm install
        
        # All projects have build-dist script.
        npm run build-dist

    - name: Start terminal session (post build)
      if: fromJSON(inputs.vars).TERMINAL_POST_BUILD == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Test
      shell: bash
      run: |
        # Not all projects have test script.
        npm run test --if-present

    - name: Publish
      # Publish is valid only for release publication.
      if: github.event_name == 'release' && github.event.action == 'published'
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ fromJSON(inputs.secrets).NODE_AUTH_TOKEN }}
      run: |
        # Create .npmignore to exclude hidden directories.
        echo /.\*/ > .npmignore
        
        npm publish --access public
