name: Build, test, publish
description: Build, optionally test, and optionally publish to NPM

inputs:
  secrets:
    description: JSON representation of workflow secrets object
    required: true
  vars:
    description: JSON representation of workflow vars object
    required: true

runs:
  using: composite

  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ fromJSON(inputs.vars).NODE_VERSION }}
        registry-url: https://registry.npmjs.org/

    - name: Checkout
      uses: actions/checkout@v4

    - name: Start terminal session (pre build)
      if: fromJSON(inputs.vars).TERMINAL_PRE_BUILD == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Build
      shell: bash
      run: |
        # Removing package-lock.json is necessary to force download of all dependencies including linked dependencies.
        rm package-lock.json
        
        npm install
        
        # This is necessary to work around platform-specific optional dependencies bug
        # (https://github.com/npm/cli/issues/4828).
        npm install @rollup/rollup-linux-x64-gnu

        # All projects have build script.
        npm run build

    - name: Start terminal session (post build)
      if: fromJSON(inputs.vars).TERMINAL_POST_BUILD == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Test
      shell: bash
      run: |
        # Project must have test script.
        # Not all projects have test script.
        npm run test --if-present

    - name: Publish
      # Publish is valid only as part of release.
      if: github.event_name == 'release'
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ fromJSON(inputs.secrets).NODE_AUTH_TOKEN }}
      run: |
        npm publish --access public
