name: Build and publish

on:
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean install
        run: |
          npm ci

      - name: Build and publish dev
        uses: ./.github/actions/build-publish
        with:
          project: dev
          no_test: true
          node_auth_token: ${{ secrets.NODE_AUTH_TOKEN }}
          terminal_pre_build: ${{ vars.TERMINAL_PRE_BUILD }}
          terminal_post_build: ${{ vars.TERMINAL_POST_BUILD }}
